### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by long0621** [dipendrashekhawat/AspNetCoreWebAppMongoDB#1]
hi, Im a new beginner for .net core and mongoDB,  and I'm search the example on github for practice these days, then I find your project, looks simple and easy forlearning, if have some problem, wish we can discuss it, thanks!

**Comment by dipendrashekhawat** [comment]
Hey, Thanks for reaching out. Yes, sure we can discuss if there is anything I can help you with.

**Comment by long0621** [comment]
yes, later i find its mongoDB's error, the Id numbers need to suit 24 digit as its defined. i ready use try /catch  to catch this error in UserService, do you know how to catch this System.FormatException?  i want show its message : "5' is not a valid 24 digit hex string." to the client .

**Comment by dipendrashekhawat** [comment]
You can add a specific catch block for cathing the FormatException and when the control is within that catch block you can show message to the client.
